# anomalib==1.1.1
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: null
  # logger:
  #   class_path: anomalib.loggers.AnomalibWandbLogger
  #   init_args:
  #     name: patchcore_cxjzq
  #     save_dir: .
  #     version: null
  #     offline: false
  #     dir: null
  #     id: null
  #     anonymous: null
  #     project: null
  #     log_model: false
  #     prefix: ''
  #     checkpoint_name: null
  #     job_type: null
  #     config: null
  #     entity: null
  #     reinit: null
  #     tags: null
  #     group: null
  #     notes: null
  #     magic: null
  #     config_exclude_keys: null
  #     config_include_keys: null
  #     mode: null
  #     allow_val_change: null
  #     resume: null
  #     force: null
  #     tensorboard: null
  #     sync_tensorboard: null
  #     monitor_gym: null
  #     save_code: null
  #     settings: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 300
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
normalization:
  normalization_method: MIN_MAX
task: SEGMENTATION
metrics:
  image:
  - F1Score
  - AUROC
  pixel: null
  threshold:
    class_path: anomalib.metrics.F1AdaptiveThreshold
    init_args:
      default_value: 0.5
      thresholds: null
      ignore_index: null
      validate_args: true
      compute_on_cpu: false
      dist_sync_on_step: false
      sync_on_compute: true
      compute_with_cache: true
logging:
  log_graph: true
default_root_dir: .
ckpt_path: null
data:
  class_path: anomalib.data.Folder
  init_args:
    name: test/zdp
    normal_dir: D:\data\wuhu\patchcore_dataset\zdp_train_data\images\train
    root: null
    abnormal_dir: null
    normal_test_dir: D:\data\wuhu\patchcore_dataset\zdp_train_data\images\train
    mask_dir: null
    normal_split_ratio: 0.2
    extensions: null
    train_batch_size: 4
    eval_batch_size: 4
    num_workers: 8
    image_size:
    - 500
    - 500
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: synthetic
    test_split_ratio: 0.3
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    seed: 666
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
    - layer2
    - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
